# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{doesfollow}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Anil Wadghule"]
  s.date = %q{2010-08-14}
  s.default_executable = %q{doesfollow}
  s.description = %q{Simple gem to show 'does follow' status of twitter users.}
  s.email = %q{anildigital@gmail.com}
  s.executables = ["doesfollow"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/doesfollow",
     "doesfollow.gemspec",
     "lib/doesfollow.rb",
     "spec/doesfollow_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/anildigital/doesfollow}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple gem to show 'does follow' status of twitter users}
  s.test_files = [
    "spec/doesfollow_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<rest-client>, [">= 1.6.0"])
      s.add_development_dependency(%q<json>, [">= 1.4.4"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<rest-client>, [">= 1.6.0"])
      s.add_dependency(%q<json>, [">= 1.4.4"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<rest-client>, [">= 1.6.0"])
    s.add_dependency(%q<json>, [">= 1.4.4"])
  end
end

